apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-service
  namespace: default
  labels:
    app: point-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-service
  template:
    metadata:
      labels:
        app: point-service
    spec:
      containers:
        - name: point-service
          image: 051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/cj-ecr:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-redis-secret
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      nodeSelector:
        eks.amazonaws.com/nodegroup: point-node-group
      imagePullSecrets:
        - name: ecr-creds
