spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-service
  template:
    metadata:
      labels:
        app: point-service
    spec:
      containers:
        - name: point-service
          image: 051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/cj-ecr:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-redis-secret
      nodeSelector:
        eks.amazonaws.com/nodegroup: point-node-group  # 🔥 여기가 핵심
      imagePullSecrets:
        - name: ecr-creds
