apiVersion: v1
kind: Service
metadata:
  name: point-service
  namespace: default
  labels:
    app: point-service
spec:
  selector:
    app: point-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080