spring:
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: false
      file: ./docker/docker-compose.yml
      lifecycle-management: start-only
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379