spring:
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: true
      file: ./docker/docker-compose.yml
      lifecycle-management: start-only
  datasource:
    url: jdbc:mysql://localhost:3306/cj
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379