server:
  port: 8082

spring:
  application:
    name: point-service

  # 포인트 서비스가 연결할 DB 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/point_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: {your_password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true