spring:
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: false
      file: ./docker/docker-compose.yml
      lifecycle-management: start-only
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cj-dev-mysql.c5syk8q4mlad.ap-northeast-2.rds.amazonaws.com:3306/cj
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config  # ✅ 이게 핵심
  api-docs:
    path: /v3/api-docs
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG