apiVersion: apps/v1
kind: Deployment
metadata:
  name: cj-app
  labels:
    app: cj-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cj-app
  template:
    metadata:
      labels:
        app: cj-app
    spec:
      containers:
        - name: cj-app
          image: 051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/cj-ecr:dev
          ports:
            - containerPort: 8080
          envFrom:  # ✅ 반드시 containers 내부!
            - secretRef:
                name: db-redis-secret
      imagePullSecrets:
        - name: ecr-creds
