apiVersion: v1
kind: Service
metadata:
  name: cj-app-service
  labels:
    app: cj-app
spec:
  selector:
    app: cj-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
