apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: multi-service-router
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - main-gateway
  http:
    - match:
        - uri:
            prefix: /user
      route:
        - destination:
            host: user-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /point
      route:
        - destination:
            host: point-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /product
      route:
        - destination:
            host: product-service
            port:
              number: 8080
    - match:
        - uri:
            prefix: /app
      route:
        - destination:
            host: cj-app-service
            port:
              number: 8080
